# Generated by Django 4.1.7 on 2023-03-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_post_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='type',
        ),
    ]
